-- src/main/resources/db/migration/V5__login_attempts.sql
-- Table to track failed login attempts for brute-force protection

CREATE TABLE IF NOT EXISTS login_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    failed_attempts INT NOT NULL DEFAULT 0,
    last_attempt_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_username FOREIGN KEY (username) REFERENCES users(username) ON DELETE CASCADE
);

CREATE INDEX idx_login_attempts_username ON login_attempts (username);
CREATE INDEX idx_login_attempts_time ON login_attempts (last_attempt_time);
